name: Assemble and Collect Metrics

on:
  workflow_call:
    inputs:
      task:
        required: true
        type: string
      kotlintask:
        required: true
        type: string
      tasks:
        required: true
        type: string
      kotlintasks:
        required: true
        type: string
    secrets:
      PRIVATE_KEY_2:
        required: true
      MY_JSON_SECRET:
        required: true
      INFLUX_URL:
        required: true
      INFLUX_TOKEN:
        required: true
      INFLUX1_URL:
        required: true
      CACHE_URL:
        required: true

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.PRIVATE_KEY_2 }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Execute assemble
        env:
          ACCESS_TOKEN: $(gcloud auth application-default print-access-token)
          PREDICTION: ${{ inputs.task }}
          PREDICTION2: ${{ inputs.kotlintask }}
          MY_JSON_SECRET: ${{ secrets.MY_JSON_SECRET }}
          INFLUX_URL: ${{ secrets.INFLUX_URL }}
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
          INFLUX1_URL: ${{ secrets.INFLUX1_URL }}
          CACHE_URL: ${{ secrets.CACHE_URL }}
          CI: true
        run: |
          gradle_prediction=${{ inputs.task }}
          kotlin_prediction=${{ inputs.kotlintask }}
          echo "PREDICTION output: ${{ inputs.task }}"
          echo "PREDICTION2 output: ${{ inputs.kotlintask }}"
          echo "$MY_JSON_SECRET" > key.json
          echo "the prediction is: $PREDICTION"
          echo "the prediction2 is: $PREDICTION2"
          echo '### Capacity Prediction Capacity Gradle ${{ inputs.task }} 🚀' >> $GITHUB_STEP_SUMMARY
          echo '### Capacity Prediction Kotlin ${{ inputs.kotlintask }} 🚀' >> $GITHUB_STEP_SUMMARY
          git pull origin main
          ./gradlew assembleDebug
          value=$(cat capacityGradle)
          tasks_executed=$(cat tasks_executed)
          kotlin_tasks_executed=$(cat kotlin_tasks_executed)
          predicted_tasks_executed=${{ inputs.tasks }}
          predicted_kotlin_tasks_executed=${{ inputs.kotlintasks }}
          valuekotlin=$(cat capacityKotlin)
          echo "### Capacity Real Value Capacity Gradle- $value 🚀" >> $GITHUB_STEP_SUMMARY
          echo "### Capacity Real Value Capacity Kotlin - $valuekotlin 🚀" >> $GITHUB_STEP_SUMMARY
          curl -X POST -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" -H "Content-Type: application/json" -d '{
              "query": "INSERT INTO `cache-node.mobile_build_metrics.results_prediction`  (capacity_gradle, predicted_gradle, capacity_kotlin, predicted_kotlin, total_tasks_executed, predicted_tasks_executed, total_kotlin_tasks_executed, predicted_kotlin_tasks_executed, created_at) VALUES ( \"'$value'\", \"'$gradle_prediction'\", \"'$valuekotlin'\", \"'$kotlin_prediction'\", \"'$tasks_executed'\", \"'$predicted_tasks_executed'\", \"'$kotlin_tasks_executed'\", \"'$predicted_kotlin_tasks_executed'\", CURRENT_TIMESTAMP());",
                          "useLegacySql": false
               }' https://bigquery.googleapis.com/bigquery/v2/projects/cache-node/queries 