name: Assemble and Collect Metrics

on:
  workflow_call:
    inputs:
      task:
        required: true
        type: string
      kotlintask:
        required: true
        type: string
      tasks:
        required: true
        type: string
      kotlintasks:
        required: true
        type: string
    outputs:
      value:
        description: "Capacity Gradle value"
        value: ${{ jobs.assemble.outputs.value }}
      valuekotlin:
        description: "Capacity Kotlin value"
        value: ${{ jobs.assemble.outputs.valuekotlin }}
      tasks_executed:
        description: "Tasks executed"
        value: ${{ jobs.assemble.outputs.tasks_executed }}
      kotlin_tasks_executed:
        description: "Kotlin tasks executed"
        value: ${{ jobs.assemble.outputs.kotlin_tasks_executed }}
    secrets:
      PRIVATE_KEY_2:
        required: true
      MY_JSON_SECRET:
        required: true
      INFLUX_URL:
        required: true
      INFLUX_TOKEN:
        required: true
      INFLUX1_URL:
        required: true
      CACHE_URL:
        required: true

jobs:
  assemble:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.execute.outputs.value }}
      valuekotlin: ${{ steps.execute.outputs.valuekotlin }}
      tasks_executed: ${{ steps.execute.outputs.tasks_executed }}
      kotlin_tasks_executed: ${{ steps.execute.outputs.kotlin_tasks_executed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Execute assemble
        id: execute
        env:
          PREDICTION: ${{ inputs.task }}
          PREDICTION2: ${{ inputs.kotlintask }}
          MY_JSON_SECRET: ${{ secrets.MY_JSON_SECRET }}
          INFLUX_URL: ${{ secrets.INFLUX_URL }}
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
          INFLUX1_URL: ${{ secrets.INFLUX1_URL }}
          CACHE_URL: ${{ secrets.CACHE_URL }}
          CI: true
        run: |
          gradle_prediction=${{ inputs.task }}
          kotlin_prediction=${{ inputs.kotlintask }}
          echo "PREDICTION output: ${{ inputs.task }}"
          echo "PREDICTION2 output: ${{ inputs.kotlintask }}"
          echo "$MY_JSON_SECRET" > key.json
          echo "the prediction is: $PREDICTION"
          echo "the prediction2 is: $PREDICTION2"
          echo '### Capacity Prediction Capacity Gradle ${{ inputs.task }} 🚀' >> $GITHUB_STEP_SUMMARY
          echo '### Capacity Prediction Kotlin ${{ inputs.kotlintask }} 🚀' >> $GITHUB_STEP_SUMMARY
          git pull origin main
          ./gradlew assembleDebug
          value=$(cat capacityGradle)
          tasks_executed=$(cat tasks_executed)
          kotlin_tasks_executed=$(cat kotlin_tasks_executed)
          predicted_tasks_executed=${{ inputs.tasks }}
          predicted_kotlin_tasks_executed=${{ inputs.kotlintasks }}
          valuekotlin=$(cat capacityKotlin)
          echo "### Capacity Real Value Capacity Gradle- $value 🚀" >> $GITHUB_STEP_SUMMARY
          echo "### Capacity Real Value Capacity Kotlin - $valuekotlin 🚀" >> $GITHUB_STEP_SUMMARY
          echo "value=$value" >> "$GITHUB_OUTPUT"
          echo "valuekotlin=$valuekotlin" >> "$GITHUB_OUTPUT"
          echo "tasks_executed=$tasks_executed" >> "$GITHUB_OUTPUT"
          echo "kotlin_tasks_executed=$kotlin_tasks_executed" >> "$GITHUB_OUTPUT"

  store_metrics:
    needs: assemble
    uses: ./.github/workflows/bigquery-metrics.yml
    with:
      value: ${{ needs.assemble.outputs.value }}
      gradle_prediction: ${{ inputs.task }}
      valuekotlin: ${{ needs.assemble.outputs.valuekotlin }}
      kotlin_prediction: ${{ inputs.kotlintask }}
      tasks_executed: ${{ needs.assemble.outputs.tasks_executed }}
      predicted_tasks_executed: ${{ inputs.tasks }}
      kotlin_tasks_executed: ${{ needs.assemble.outputs.kotlin_tasks_executed }}
      predicted_kotlin_tasks_executed: ${{ inputs.kotlintasks }}
    secrets:
      PRIVATE_KEY_2: ${{ secrets.PRIVATE_KEY_2 }} 