name: Store BigQuery Metrics

on:
  workflow_call:
    inputs:
      value:
        required: true
        type: string
      gradle_prediction:
        required: true
        type: string
      valuekotlin:
        required: true
        type: string
      kotlin_prediction:
        required: true
        type: string
      tasks_executed:
        required: true
        type: string
      predicted_tasks_executed:
        required: true
        type: string
      kotlin_tasks_executed:
        required: true
        type: string
      predicted_kotlin_tasks_executed:
        required: true
        type: string
    secrets:
      PRIVATE_KEY_2:
        required: true

jobs:
  store_metrics:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.PRIVATE_KEY_2 }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Store Metrics in BigQuery
        env:
          ACCESS_TOKEN: $(gcloud auth application-default print-access-token)
        run: |
          curl -X POST -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" -H "Content-Type: application/json" -d '{
              "query": "INSERT INTO `cache-node.mobile_build_metrics.results_prediction`  (capacity_gradle, predicted_gradle, capacity_kotlin, predicted_kotlin, total_tasks_executed, predicted_tasks_executed, total_kotlin_tasks_executed, predicted_kotlin_tasks_executed, created_at) VALUES ( \"'${{ inputs.value }}'\", \"'${{ inputs.gradle_prediction }}'\", \"'${{ inputs.valuekotlin }}'\", \"'${{ inputs.kotlin_prediction }}'\", \"'${{ inputs.tasks_executed }}'\", \"'${{ inputs.predicted_tasks_executed }}'\", \"'${{ inputs.kotlin_tasks_executed }}'\", \"'${{ inputs.predicted_kotlin_tasks_executed }}'\", CURRENT_TIMESTAMP());",
              "useLegacySql": false
          }' https://bigquery.googleapis.com/bigquery/v2/projects/cache-node/queries 