name: Generate Cache Key

on:
  workflow_call:
    outputs:
      cache_key:
        description: "Generated cache key"
        value: ${{ jobs.generate_cache_key.outputs.cache_key }}

jobs:
  generate_cache_key:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
    timeout-minutes: 60
    outputs:
      cache_key: ${{ steps.generate_cache_key.outputs.cache_key }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Cache Key
        id: generate_cache_key
        run: |
          all_contents=""
          while IFS= read -r -d '' file; do
            all_contents+=$(cat "$file")
          done < <(find . -name "build.gradle.kts" -print0)
          cache_key=$(echo -n "$all_contents" | sha256sum | awk '{print $1}')
          echo "Cache Key: $cache_key"
          echo "cache_key=$cache_key" >> "$GITHUB_OUTPUT"

      - name: Check for Cached File
        id: cache
        uses: actions/cache@v4
        with:
          path: project_graph.dot
          key: gradle-cache-file-${{ steps.generate_cache_key.outputs.cache_key }}
        continue-on-error: true

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Generate File if Cache is Not Found
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "Cache not found, generating file..."
          ./gradlew generateModulesGraphvizText -Pmodules.graph.output.gv=project_graph.dot
          cat project_graph.dot
        env:
          MY_JSON_SECRET: ${{ secrets.MY_JSON_SECRET }}
          INFLUX_URL: ${{ secrets.INFLUX_URL }}
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
          INFLUX1_URL: ${{ secrets.INFLUX1_URL }}
          CACHE_URL: ${{ secrets.CACHE_URL }}
          CI: true

      - name: Cache the Generated File
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: project_graph.dot
          key: gradle-cache-file-${{ steps.generate_cache_key.outputs.cache_key }} 