name: Build CI

on:
    push:
        branches:
            - test_12

concurrency:
    group: build-${{ github.ref }}
    cancel-in-progress: true

jobs:

    files_that_going_to_be_updated:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: 17

            - name: Check for Cached File
              id: cache
              uses: actions/cache@v3
              with:
                  path: project_graph.dot
                  key: gradle-cache-file-${{ steps.generate_cache_key.outputs.cache_key }}

            - name: Execute Assemble
              run: |
                  git pull origin test_12
                  git log -n 2
                  ./modulesbychange --dot-file project_graph.dot
                  cat potential_tasks_executed.txt
              env:
                  MY_JSON_SECRET: ${{ secrets.MY_JSON_SECRET }}


            - name: Set up Google Cloud Credentials
              env:
                  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
                  MY_JSON_SECRET: ${{ secrets.MY_JSON_SECRET }}
              run: |
                  echo "$MY_JSON_SECRET" > key.json
                  export GOOGLE_APPLICATION_CREDENTIALS=key.json
                  ACCESS_TOKEN=$(curl -s -X POST -H "Content-Type: application/json" \
                  -d @key.json \
                  https://oauth2.googleapis.com/token | jq -r '.access_token')
                  curl -X POST \
                  -H "Authorization: Bearer $ACCESS_TOKEN" \
                  -H "Content-Type: application/json" \
                  -d '{
                      "query": "SELECT * FROM ML.PREDICT(MODEL `cache-node.mobile_build_metrics.model_builds_7`,( SELECT 3403 as tasksExecuted));",
                      "useLegacySql": false
                    }' \
                  https://bigquery.googleapis.com/bigquery/v2/projects/cache-node/queries




