name: Build CI

on:
  push:
    branches: [ main]
  schedule:
      - cron: '0 */4 * * *'    

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  newcommit:
    strategy:
      matrix:
        java: [17]

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version:  ${{ matrix.java }}

      - name: Execute assemble
        run: |
          bash replacer
          git config user.email inaki.seri@gmail.com
          git config user.name "inaki"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/cdsap/AwesomeApp

          git add .
          git commit -m "change $RANDOM"
          git push origin main


  assemble:
    runs-on: "ubuntu-latest"
    needs: [ newcommit]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version:  17

      - name: Execute assemble
        run: |
          git log -1
          ./gradlew assembleDebug --info
        env:
            INFLUX_URL: ${{ secrets.INFLUX_URL }}
            INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
            CACHE_URL: ${{ secrets.CACHE_URL }}
            CI: true

  lint:
    runs-on: "ubuntu-latest"
    needs: [ newcommit]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version:  17

      - name: Execute lintRelease
        run: |
          ./gradlew lintRelease
        env:
            INFLUX_URL: ${{ secrets.INFLUX_URL }}
            INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
            CACHE_URL: ${{ secrets.CACHE_URL }}
            CI: true


  testDebug:
    runs-on: "ubuntu-latest"
    needs: [ newcommit]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version:  17

      - name: Execute testDebug
        run: |
          ./gradlew testDebug
        env:
            INFLUX_URL: ${{ secrets.INFLUX_URL }}
            INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
            CACHE_URL: ${{ secrets.CACHE_URL }}
            CI: true
