name: Build CI

on:
    schedule:
        - cron: '0 */2 * * *'

concurrency:
    group: build-${{ github.ref }}
    cancel-in-progress: true

jobs:
    generate_cache_key:
        uses: ./.github/workflows/cache-key.yml
        secrets: inherit

    newcommit:
        needs: generate_cache_key
        uses: ./.github/workflows/commit.yml
        secrets: inherit

    files_that_going_to_be_updated:
        needs: newcommit
        uses: ./.github/workflows/file-changes.yml
        secrets: inherit

    gcloud_query:
        needs: files_that_going_to_be_updated
        uses: ./.github/workflows/gcloud-query.yml
        secrets: inherit

    assemble:
        needs: [gcloud_query, files_that_going_to_be_updated]
        uses: ./.github/workflows/assemble.yml
        secrets: inherit


