name: Create New Commit

on:
  workflow_call:

jobs:
  newcommit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Push Changes
        run: |
          bash replacer
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/cdsap/AwesomeApp
          git add .
          git commit -m "change $RANDOM"
          git push origin main 